[package]
name = "liturgy-backend"
version = "0.1.0"
edition = "2024"
readme = "README.md"
homepage = "https://liturgy.ericbreyer.com"
repository = "https://github.com/ericbreyer/liturgy"
documentation = "https://docs.rs/liturgy-backend"
keywords = ["liturgy", "backend", "liturgical-calendar"]
categories = ["web-programming"]
description = "HTTP API server that provides calendar data and serves the frontend for the Liturgy project."
license = "MIT OR Apache-2.0"

[dependencies]
# local crates
calendar_calc = { path = "../calendar_calc", version = "0.1.0" }
types = { path = "../types", version = "0.1.0" }

chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
anyhow = "*"
clap = { version = "4", features = ["derive"] }
serde_json = "1.0"
indexmap = ">=2.0"

# Web dependencies
axum = "0.8"
tokio = { version = "1.48", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["fs", "cors", "trace"] }
tracing-subscriber = "0.3"

[dev-dependencies]
test-case = "3.3"
insta = "1.43"
reqwest = { version = "0.12", features = ["json", "native-tls"] }
tempfile = "3.23"

[lints]
workspace = true
