[package]
name = "types"
version = "0.1.0"
edition = "2024"
readme = "README.md"
homepage = "https://liturgy.ericbreyer.com"
repository = "https://github.com/ericbreyer/liturgy"
keywords = ["types", "dto", "liturgy"]
categories = ["data-structures"]
description = "Shared types and DTOs for the Liturgy workspace."
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1.0", features = ["derive", "rc"] }
chrono = "0.4"

[lints]
workspace = true
