[package]
name = "calendar_calc"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive", "rc"] }
toml = ">=0.9.5"
bitflags = { version = ">=2.0", features = ["serde"] }
anyhow = "*"
itertools = "0.14.0"
types = { path = "../types" }

[dev-dependencies]
test-case = "3.3"
insta = {version = "1.43", features = ["filters"]}
rayon = "1.11.0"
cross-proc-cache = { path = "../cross-proc-cache" }

[build-dependencies]
rand = "0.8"

[lints]
workspace = true