id = "octave-of-christmas"
name = "Octave of Christmas"

[vespers]
antiphons = "Octave of Christmas"
psalms = "Octave of Christmas"
chapter = "Octave of Christmas"
hymn = "Octave of Christmas"
verse = "Octave of Christmas"
magnificat_antiphon = "Octave of Christmas"
collect = "Octave of Christmas"
