id = "commemoration-of-the-baptism-of-our-lord-jesus-christ"

[vespers]
antiphons = "Proper"
psalms = "Proper"
chapter = "Proper"
hymn = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"
collect = "Proper"