id = "octave-day-of-the-nativity-of-our-lord-jesus-christ"

[first_vespers]
antiphons = "Proper"
psalms = "Common of the Blessed Virgin Mary"
chapter = "Proper"
hymn = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"
collect = "Proper"

[vespers]
antiphons = "Proper"
psalms = "Common of the Blessed Virgin Mary"
chapter = "Proper"
hymn = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"
collect = "Proper"