id = "the-most-holy-name-of-jesus"

[first_vespers]
antiphons = "Proper"
psalms = "Sunday w.115"
chapter = "Proper"
hymn = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"
collect = "Proper"

[vespers]
antiphons = "Proper"
psalms = "Proper"
chapter = "Proper"
hymn = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"
collect = "Proper"
