id = "the-immaculate-conception-of-the-blessed-virgin-mary"

[vespers]
antiphons = "Proper"
chapter = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"

[first_vespers]
antiphons = "Proper"
chapter = "Proper"
verse = "Proper"
magnificat_antiphon = "Proper"